### ISSUE TITLE
The button is missing

### ISSUE THREAD

**Issue by lordbagel42** [SrS2225a/BetterDiscord#20] opened 2022-12-30 23:10 UTC
title says it all

**Comment by SrS2225a** [comment] 2023-01-06 05:32
Are you referring to issue #18? You will see there why that plugin does not work, and why it has not been for a while. Sorry about the inconvenience of all this

**Comment by lordbagel42** [comment] 2023-01-07 01:30
I would be, I couldn't find it because apparently I'm blind

**Comment by SrS2225a** [comment] 2023-01-07 21:44
I see, in this case I will close this issue as it is a duplicate of the other one. But dont worry, I am trying to fix it asap. The Quick Switcher turned out to be a little harder to patch then I first thought

**Closed by SrS2225a** 2023-01-07 21:44 UTC
